### ISSUE TITLE
Question about the voxel data

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#21]
I am not sure about how the voxel data is generated. 
Is it generated using the `obj` file related to it?
During training, do you rotate the voxel predicted by the network?
And how do you determine the scale of the voxel?

**Comment by gkioxari** [comment]
The voxel data for Pix3D and ShapeNet are provided in the datasets. If you need to generate your own voxels, you can generate so using the [binvox](http://www.patrickmin.com/binvox/) voxelization code with the following parameters:
```
binvox -aw -dc -pb  # for solid voxelizations
binvox -aw -dc -pb -ri  # for surface-only voxelizations
```

The currently distributed ShapeNet voxelizations (at 128^3 resolution) were computed at 256^3 and then downsampled to 128^3 by adding the `-down` argument to the two commands:
```
binvox -aw -dc -down -pb  # for solid voxelizations
binvox -aw -dc -down -pb -ri  # for surface-only voxelizations
```
If you use the viewvox code to view these voxelizations please note that it requires the `-ki` command line argument in order to visualize the solid voxelizations.

**Comment by KunalMGupta** [comment]
In case someone is wondering where to find ShapeNet voxel data, check this out:
https://shapenet.org/qaforum/index.php?qa=101&qa_1=model-presolid-binvox-files-for-shapenetcore-v1

**Comment by gkioxari** [comment]
Before downloading this data, you should register and obtain permission from the ShapeNet team. This is the reason why we don't provide a link to the data for download directly. And the ShapeNet team asked us to not distribute the link to the data.

**Comment by gkioxari** [comment]
@zshyang You have not responded to this issue and I am not sure whether your question has been addressed. I will be closing this issue and if you need to follow-up, please re-open it.

**Comment by zshyang** [comment]
Thanks a lot! You solved my problem!
