### ISSUE TITLE
question about batch_crop_voxels_within_box

### ISSUE THREAD

**Issue by Sekunde** [facebookresearch/meshrcnn#33]
Thanks for sharing the great code!

I am trying to train meshrcnn on ScanNet, where each image has more instances than Pix3D.

I found this line of code tries to stack a list of voxels into (batch_size, n, 3)

https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/meshrcnn/structures/voxel.py#L23

how do you make sure that each instance in the list has the same amount of voxels so that they can be stacked? or in the training, it is assumed that there is only 1 instance in the image?

**Comment by gkioxari** [comment]
Hi @Sekunde 
The voxels data holds `n` points for each voxel in the batch. This `n` can come from your voxel annotations. In both shapenet and pix3D voxels come at a fixed resolution, e.g. 128^3, so `n = 128^3`. These points are then converted into voxels via a simple voxelization op. 
I presume you are asking this question because ScanNet gives different voxel resolutions per object. In this case, I advocate for a different data structure than the one in the code, for example the pointclouds data structure in PyTorch3D can hold heterogeneous batches of pointclouds. 

https://github.com/facebookresearch/pytorch3d/blob/e3819a49dfa855de1a7c99c0583fb69f9bdad75b/pytorch3d/structures/pointclouds.py#L9

We wrote Mesh R-CNN before these new features in PyTorch3D. If I were to rewrite it, I'd use pointclouds so that we can hold a variable number of points per element in the batch. Of course, these points will be converted to a fixed resolution voxel, e.g. 24^3 for Mesh R-CNN, when constructing the ground truth voxel targets.

**Comment by Sekunde** [comment]
thanks for the detailed explanation and advice for a potential solution.
