### ISSUE TITLE
Add depth channel

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#48]
Hi,

I was trying to add one more channel at the input. That channel is a depth channel. I hope by adding it the mesh quality could be improved. 

But it turns out that the results of adding one more channel are making the results worse. The box AP, mask AP, and mesh AP are worse.

My question is:
1. Is it because of the loaded ResNet?
2. During training, I am not sure whether the weights of ResNet is open or frozen. Could you help me with it? I saw some parameters called `DEFORM` in the `yaml` file.

Best regards

**Comment by gkioxari** [comment]
If you are changing the image input from RGB to RGBD how are you initializing the first layer? If the shape doesn't match and it won't because the expected number of channels is 3 and you give it 4, it won't initialize from the pre-trained weights. You need to check that. 
Now, having said that, this repo is for issues with the codebase. I can't consult on your projects or with things you hope to do that diverge from the recipe in this codebase.

**Comment by zshyang** [comment]
Okay, forgive me.
Let's change the way of asking. 
Do the weights of ResNet change during the training of Mesh R-CNN on ShapeNet?

**Comment by gkioxari** [comment]
They do change. We train end-to-end. If you need to freeze part of the weights, look at detectron2 on how that's done.

**Comment by zshyang** [comment]
Thanks!
