### ISSUE TITLE
Questions on Voxel head an V count

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#49]
Hi, 

I have a couple questions about the voxel head and the number of vertices in the final mesh.

1. In the paper you say "_On ShapeNet, the Voxel-Only baseline is trained with a batch size of 64 (vs. a batch size of 32 for our full model); on Pix3D it uses the same training recipe as our full model._" But looking at https://github.com/facebookresearch/meshrcnn/blob/master/configs/pix3d/MESH-RCNN-FPN.yaml#L51 it seems like the batch size was 16 for Pix3D. Am I reading it wrong?

2. Just right before that, in the paper, you say "_The voxel branch is the same as in the ShapeNet models (see Table 8), except that we predict voxels at a lower resolution (48×48×48 for ShapeNet vs. 24×24×24 for Pix3D) due to memory constraints._". If I understand this correctly, the max number of vertices of the final mesh is limited by the number of voxels * 8. Is this correct, and there is no densification along the edges happening (I didn't find it in the paper, sorry if I missed it) between the mesh refinement steps? 

3. If the max vertex count is truly limited by `ROI_VOXEL_HEAD.NUM_DEPTH * 3 * 8`, do you think that the quality metrics could potentially go higher than in the paper for Pix3D tests, providing one would train with a smaller batch size, but higher `ROI_VOXEL_HEAD.NUM_DEPTH` given the vRAM constraints?

**Comment by gkioxari** [comment]
Hi @dmitrykudinov 

Here are the answers to your questions. 
1. The sentence you mention says that the Voxel-Only baselines are trained with the same recipe as the corresponding full models. So for ShapeNet, the Voxel-Only baseline and the full model follow the same recipe (apart from the difference in batch size). For Pix3D, the Voxel-Only baseline and the full model follow exactly the same training recipe. The training recipes between ShapeNet and Pix3D are very different however (and I think that's what your question refers to). The first is a CNN model with one object per image. There, the batch size refers to the number of images per batch which equals the number of meshes per batch in the output. But on Pix3D, the model is a two stage detection model. There is two notions of batch size there: the image-specific part of the network accepts 2 images per batch per GPU (see `SOLVER.IMS_PER_BATCH` flag in the configs = 16 images for a 8-GPU job) and the region-specific part of the network, separated by RoIAlign from the image-specific network, accepts N regions per batch per GPU, where N is the number of object detections in the image. Please refer to detectron2 for more details.

2. Our models predict a voxel of shape `VxVxV` for every object (`V=48` for ShapeNet and `V=24` for Pix3D). The voxel output is then passed through the cubify operation and gets converted into a mesh. The size of the mesh is related to the size of the voxel (aka V) and the density of its activations. I don't know what it means to "densify along the edges". Do you mean subdivision of the mesh? We do not increase the resolution of the mesh by subdivision for our model because we found it doesn't actually help in terms of performance. The deformation is enough to capture the shape. But it is definitely possible to add subdivision in the model if you wish to. 

3. I think my answer above is relevant here. It's definitely the case that very small mesh resolution could hamper performance. In our experiments, we found that the number we ended up with was reaching max performance and further increasing resolution didn't help. This might be an effect of small data too (e.g. Pix3D is tiny) and if our dataset was larger we could have reached different conclusions.

**Comment by dmitrykudinov** [comment]
@gkioxari , thank you for the insight. Closing this one for now.

**Comment by KnightOfTheMoonlight** [comment]
@gkioxari I am still confused for the batch size setup for pix3d. Cause in your example configuration file `configs/pix3d/meshrcnn_R50_FPN.yaml` in the pix3d tutorial [https://github.com/facebookresearch/meshrcnn/blob/master/INSTRUCTIONS_PIX3D.md](https://github.com/facebookresearch/meshrcnn/blob/master/INSTRUCTIONS_PIX3D.md), there is no `  IMS_PER_BATCH:` in `SOLVER:` https://github.com/facebookresearch/meshrcnn/blob/df9617e9089f8d3454be092261eead3ca48abc29/configs/pix3d/meshrcnn_R50_FPN.yaml#L55, while in [https://github.com/facebookresearch/meshrcnn/blob/master/configs/pix3d/MESH-RCNN-FPN.yaml](https://github.com/facebookresearch/meshrcnn/blob/master/configs/pix3d/MESH-RCNN-FPN.yaml ), it has https://github.com/facebookresearch/meshrcnn/blob/df9617e9089f8d3454be092261eead3ca48abc29/configs/pix3d/MESH-RCNN-FPN.yaml#L50.
Is this just a small igorance you made for `meshrcnn_R50_FPN.yaml`?
