### ISSUE TITLE
How to train new categories

### ISSUE THREAD

**Issue by hetolin** [facebookresearch/meshrcnn#6]
Hi, thank you for sharing your work.It seems useful.
Or how could I train this network for new(other) categories?

**Comment by gkioxari** [comment]
If you have a new dataset to train on, you can easily plug it in to our pipeline and train. Make sure your data is saved at a format similar to the ones provided (for example for Mesh R-CNN save your data in a coco format as we have done for Pix3D). Then all you need to do is register it (registration happens [here](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/data/datasets/builtin.py), but you can also follow the detectron2 tutorials for more details)

**Comment by hetolin** [comment]
thank you for your answer very much. But if I want to train some categories like bottles.The model of bottle can only be found in ShapeNet, but I cannot get the rendering image and binvox files of bottle categories. So dose it mean I cannot train the meshrcnn for bottle categories for lack of dataset ? the categories in pix3D is so limited.

**Comment by gkioxari** [comment]
I will take this opportunity to expand on some basic concepts, hoping to resolve your confusion. Supervised learning tasks, such as object recognition and instance segmentation (see Detectron2), require training data of paired image and aligned semantic annotations. If you wish to extend your recognition model to be able to recognize say *butterflies*, you will need to create a training dataset of aligned images and annotated butterflies and train your model on it. Similarly, in Mesh R-CNN, in order to extend the recognition capabilities to new categories,  a training data of images and aligned 3D models for this category is needed. Coming back to your specific question, if you have a dataset of images and bottle annotations in 3D, you can train Mesh R-CNN with the code provided in this repo. 

I hope this helped! I will be closing the issue as it is not pertinent to the implementation found in this repo.

**Comment by hetolin** [comment]
Thank you for your prompt reply. Now my problem is the lack of training dataset of bottle category. I will try to create or find the datasets as you mentioned above. Greatly appreciated for your patience and guidance.

**Comment by Guo-Ling** [comment]
Have you trained dataset of bottle category successfully？
