### ISSUE TITLE
box2D_to_cuboid3D (code)

### ISSUE THREAD

**Issue by trevor-taeyeop** [facebookresearch/meshrcnn#60]
I have very a simple question related to box2D_to_cuboid3D implementation.

https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/meshrcnn/utils/shape.py#L54-L58

Q1. Can I ask why subtract 1 is necessary in this part??

Q2. Can I ask why used the **(w-px), (h-py)** instead of **(px),(py)**. 
Because It feels px, py looks simple, but your code represent (w-px),(h-py). I wonder if there is another reason.

    #Simple Version
    x1 = -(x1 - px)
    y1 = -(y1 - py)
    x2 = -(x2 - px)
    y2 = -(y2 - py)

**Comment by gkioxari** [comment]
These transforms have to do with aligning the 3D shape to the image, which requires transforming the coordinate systems from world to image etc.

**Comment by trevor-taeyeop** [comment]
Yes, thanks for the explanation. 
As I understood that this process is changing the pixel array to film plane. 
And I'm not sure why -1 is needed in this code (unlike the equation below).


![Screenshot from 2020-09-23 13-38-44](https://user-images.githubusercontent.com/50736858/94212992-b0dc2b00-ff10-11ea-8ef0-db9443fae354.png)

**Comment by gkioxari** [comment]
It's because of `x1, y1, x2, y2` in 

https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/meshrcnn/utils/shape.py#L53

Lives in the image plane ranging from `[0, W-1] x [0, H-1]`. Note that `px=w/2, py = h/2` from the calibration matrix so essentially the transformation is `x1 = w/2 - 1 - x1` (accordingly for the rest of the coordinates). So `x1=0` in image plane gets mapped to `x1=w/2-1` and similarly, the coordinate `x1=w-1` in the image plane gets mapped to `x1=-w/2`.

**Comment by trevor-taeyeop** [comment]
Thanks for explaining.
