### ISSUE TITLE
torchvision vs detectron2 ResNet backbone?

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#65]
Hi @gkioxari ,

Was there a particular reason why you [chose](https://github.com/facebookresearch/meshrcnn/blob/master/shapenet/modeling/backbone.py#L38) to use torchvision's implementation of ResNet backbone instead of Detectron2's one?

**Comment by gkioxari** [comment]
Ha!! Yes and no!
Ok so backstory to this project because I am in a good mood (!): Justin was working on the shapenet experiments and I was working on the detection + pix3d experiments. This was at a time that detectron2 was not fully there and not even released yet. So Justin was reluctant to use the existing internal version of detectron2 (as it was being heavily developed and thus changing daily) and also he loves torchvision, while I was more courageous and preferred detectron2 over torchvision (we fought about this a lot!). 
At code release time, I was too lazy to integrate and switch the torchvision backbone to detectron2, hence this distinction!

**Comment by dmitrykudinov** [comment]
:) a familiar situation. 
So, there is no inherent incompatibility between these two, good. I'll try to swap it with the Detectron2 version then, as the latter supports `input_shape` parameter (our project isn't RGB-based). 

Thank you for the prompt reply, closing this one for now.

**Comment by gkioxari** [comment]
No there is no inherent incompatibility. Just inherent laziness! 
A few caveats for when switching to Detectron2 that I can think of (in an attempt to be as helpful as possible): Make sure to do the same input transforms to the R2N2 input images

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/shapenet/data/mesh_vox.py#L47-L50

If I think of anything else I will post here! Happy to hear updates on the switch too!

**Comment by dmitrykudinov** [comment]
thank you, will do

**Comment by dmitrykudinov** [comment]
yep, as you said, it was pretty straightforward - just to update the stage names and normalization (in our case the latter was updated anyway due to the nature of the data).

![image](https://user-images.githubusercontent.com/3879467/95631162-0d266b00-0a38-11eb-9959-90594c4c382e.png)



thank you for your help!
