### ISSUE TITLE
Turning off voxel head and using your own default voxel

### ISSUE THREAD

**Issue by rezhv** [facebookresearch/meshrcnn#76]
Hi, I did some keyword searching in the closed issues but did not find anything that answers my question.
Is there a way to use mesh r-CNN without using the voxel head? Let's say I have a generic mesh (cubified voxel) that I always want to use no matter what the input RGB picture is. I then want to use the mesh refinement branch to change the initial mesh using vert-align and graph Conv.  Is there a way to achieve this?

**Comment by gkioxari** [comment]
You can set `VOXEL_ON` to False

https://github.com/facebookresearch/meshrcnn/blob/908ac99e90174dff4d2c7e4032500fed86439b2a/meshrcnn/config/config.py#L13

And then you need to make some minor changes to the code so that you use your own voxel.

**Comment by rezhv** [comment]
Thank you very much for your response. 
So my understanding is that if  cfg.MODEL.VOXEL_ON = False then by default the model uses a sphere?
Also, I would very much appreciate it if you could point out the file in which the code I'm looking for exists ( the one I need to change to use my own voxel)

**Comment by gkioxari** [comment]
I am happy to provide the pointer to the code, it follows below:

https://github.com/facebookresearch/meshrcnn/blob/908ac99e90174dff4d2c7e4032500fed86439b2a/meshrcnn/modeling/roi_heads/roi_heads.py#L71

However I am worried that if you don't understand the codebase yourself in order to identify the points you need to change then you will most likely insert bugs that you won't find out leading to a lot of wasted time. My advise to you if you want to build on top of this codebase (or any other codebase for that matter) is to familiarize yourself with it, understand the flow of the code and understand (roughly) where things happen.

**Comment by rezhv** [comment]
Thanks.
That is what I will do. 
Closing this one for now!
