### ISSUE TITLE
size_divisibility padding in resnet_fpn: accounting in T, K?

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#80]
Hi @gkioxari ,

have a quick question regarding your portion of the mesh-rcnn implementation, in particular the [ImageList-based padding in resnet_fpn backbone](https://github.com/facebookresearch/detectron2/blob/4bd27960e1c56eb8950b04f24c60b845d5840d8a/detectron2/modeling/meta_arch/rcnn.py#L185). Since the backbone's `size_divisibility` is 32 in case of Detectron2's resnet50 implementation, if I read it correctly, the images are padded with up to 31px in WH dims. But I could not find the corresponding adjustment in K and T matrices [in your code](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/modeling/roi_heads/roi_heads.py#L133). 
Do you think that the incoming `features` resolution isn't high enough to be affected by ImageList' padding? Or am I missing something else here?

thank you.

**Comment by gkioxari** [comment]
The padding in the images does not affect the final features since the image to feature and roi alignment is preserved after the conv2d computations in the CNN.

**Comment by dmitrykudinov** [comment]
I see, this explains it for the T matrix then. How about K? Wouldn't the padding affect the focal length value (view angle) needed for conversion from voxel to world space?

**Comment by gkioxari** [comment]
No it does not. The padding does not change the input image, it just allows for Detectron2 to accept batches of images, without changing the aspect ratio of the image (a change in aspect ratio would actually affect K, but now it doesn't). At the end, image features -> rois -> voxels are perfectly aligned and aligned with the world.

**Comment by dmitrykudinov** [comment]
Got it.
>a change in aspect ratio would actually affect K, but now it doesn't
Interesting. Is it starting with a specific version of Detectron2?

**Comment by dmitrykudinov** [comment]
Also, a connected question - I see [you are using flipping and resizing](https://github.com/facebookresearch/meshrcnn/blob/d59029ee819bda32f00354af2e5fcdb2223d23fd/meshrcnn/data/meshrcnn_transforms.py#L284) for augmentation. Why did you decide not to use random rotations along Z axis?

**Comment by gkioxari** [comment]
> Interesting. Is it starting with a specific version of Detectron2?

The function that inputs the images to list basically allocates a tensor of shape (max(h), max(w)) and stores the images without any distortion. That is the pipeline used for state-of-the-art object detection. It is different than what was used in the past, or from object classification, where images are usually distorted to fit a certain aspect ratio, and this also changes the properties of objects.

> Also, a connected question - I see you are using flipping and resizing for augmentation. Why did you decide not to use random rotations along Z axis?

Good question! I am borrowing all the augmentation done in object detection. We have not found rotation along Z to be helpful in 2D so we are not doing that. But it might be useful for this task, not only because of its 3D nature but also because the data is limited!

**Comment by dmitrykudinov** [comment]
Thank you for detailed and prompt replies. Closing.
